In [20]:
import pandas as pd 
import matplotlib.pyplot as plt

In [21]:
df = pd.read_csv("Data/upi_transactions.csv")
df.head()

,transaction id,transaction_date,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank
0,TXN0000000001,08-10-2024 15:17,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis
1,TXN0000000002,11-04-2024 06:56,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI
2,TXN0000000003,02-04-2024 13:27,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank
3,TXN0000000004,07-01-2024 10:09,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI
4,TXN0000000005,23-01-2024 19:04,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  object
 1   transaction_date    250000 non-null  object
 2   transaction type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
dtypes: int64(1), object(9)
memory usage: 19.1+ MB

In [23]:
df["transaction_date"] = pd.to_datetime(
    df["transaction_date"],
    format = "%d-%m-%Y %H:%M"
)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250000 entries, 0 to 249999
Data columns (total 10 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   transaction id      250000 non-null  object
 1   transaction_date    250000 non-null  datetime64[ns]
 2   transaction type    250000 non-null  object
 3   merchant_category   250000 non-null  object
 4   amount (INR)        250000 non-null  int64
 5   transaction_status  250000 non-null  object
 6   sender_age_group    250000 non-null  object
 7   receiver_age_group  250000 non-null  object
 8   sender_state        250000 non-null  object
 9   sender_bank         250000 non-null  object
dtypes: datetime64[ns](1), int64(1), object(8)
memory usage: 19.1+ MB

In [24]:
df  = df.set_index("transaction_date")
df.head()

,transaction id,transaction type,merchant_category,amount (INR),transaction_status,sender_age_group,receiver_age_group,sender_state,sender_bank
transaction_date,,,,,,,,,
2024-10-08 15:17:00,TXN0000000001,P2P,Entertainment,868,SUCCESS,26-35,18-25,Delhi,Axis
2024-04-11 06:56:00,TXN0000000002,P2M,Grocery,1011,SUCCESS,26-35,26-35,Uttar Pradesh,ICICI
2024-04-02 13:27:00,TXN0000000003,P2P,Grocery,477,SUCCESS,26-35,36-45,Karnataka,Yes Bank
2024-01-07 10:09:00,TXN0000000004,P2P,Fuel,2784,SUCCESS,26-35,26-35,Delhi,ICICI
2024-01-23 19:04:00,TXN0000000005,P2P,Shopping,990,SUCCESS,26-35,18-25,Delhi,Axis

In [35]:
df_index = df.set_index("transaction_id")

AttributeError: 'function' object has no attribute 'set_index'

In [26]:
df

<bound method DataFrame.sort_index of                     transaction id transaction type merchant_category  \
transaction_date
2024-10-08 15:17:00  TXN0000000001              P2P     Entertainment
2024-04-11 06:56:00  TXN0000000002              P2M           Grocery
2024-04-02 13:27:00  TXN0000000003              P2P           Grocery
2024-01-07 10:09:00  TXN0000000004              P2P              Fuel
2024-01-23 19:04:00  TXN0000000005              P2P          Shopping
...                            ...              ...               ...
2024-11-08 22:41:00  TXN0000249996         Recharge              Food
2024-12-15 02:58:00  TXN0000249997              P2P         Utilities
2024-11-27 16:33:00  TXN0000249998              P2P              Food
2024-01-05 13:31:00  TXN0000249999         Recharge        Healthcare
2024-01-17 15:23:00  TXN0000250000              P2P     Entertainment

                     amount (INR) transaction_status sender_age_group  \
transaction_date
2024-10-08 15:17:00           868            SUCCESS            26-35
2024-04-11 06:56:00          1011            SUCCESS            26-35
2024-04-02 13:27:00           477            SUCCESS            26-35
2024-01-07 10:09:00          2784            SUCCESS            26-35
2024-01-23 19:04:00           990            SUCCESS            26-35
...                           ...                ...              ...
2024-11-08 22:41:00           373            SUCCESS            36-45
2024-12-15 02:58:00          2025            SUCCESS            36-45
2024-11-27 16:33:00           468            SUCCESS            26-35
2024-01-05 13:31:00           284            SUCCESS            18-25
2024-01-17 15:23:00           531            SUCCESS            18-25

                    receiver_age_group    sender_state sender_bank
transaction_date
2024-10-08 15:17:00              18-25           Delhi        Axis
2024-04-11 06:56:00              26-35   Uttar Pradesh       ICICI
2024-04-02 13:27:00              36-45       Karnataka    Yes Bank
2024-01-07 10:09:00              26-35           Delhi       ICICI
2024-01-23 19:04:00              18-25           Delhi        Axis
...                                ...             ...         ...
2024-11-08 22:41:00              26-35       Telangana       ICICI
2024-12-15 02:58:00              26-35       Rajasthan        HDFC
2024-11-27 16:33:00              18-25     West Bengal       ICICI
2024-01-05 13:31:00              36-45  Andhra Pradesh        Axis
2024-01-17 15:23:00              26-35       Telangana        Axis

[250000 rows x 9 columns]>

In [ ]:
df["SMA_3"] = df["Sales"].rolling(window=3).mean()
df.head(10)

AttributeError: 'function' object has no attribute 'index'

In [29]:
df.index.hour

AttributeError: 'function' object has no attribute 'index'

In [28]:
df.groupby(df.index.hour)["amount (INR)"].sum()

AttributeError: 'function' object has no attribute 'groupby'